// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:3c9d7c5f706702343b2d85fdc58032c26f642dce63c2a8de24775dd2b9176eb3
// To regenerate: alef generate
// To verify freshness: alef verify

module github.com/xberg-io/tree-sitter-language-pack/packages/go/v2

go 1.26

require github.com/tree-sitter/go-tree-sitter v0.25.0

require github.com/mattn/go-pointer v0.0.1 // indirect
