// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:14f67fcf8a775bb80ee5182bc5ac3403e5fff7b89329824cc459892671e97989
// To regenerate: alef generate
// To verify freshness: alef verify

module github.com/xberg-io/tree-sitter-language-pack/packages/go

go 1.26

require github.com/tree-sitter/go-tree-sitter v0.25.0

require github.com/mattn/go-pointer v0.0.1 // indirect
