// Code generated by alef — DO NOT EDIT.
// alef:hash:bf664f3985e0a415b35416ae9d3cc1974fd33b411ab31227dc27a92ed31bfa15
package tspack

// RequireNativeSetup_2_0_0 is a version-skew sentinel referenced by the
// machine-local cgo link shim that `cmd/setup` writes into consumer packages. If this
// module is upgraded without re-running `cmd/setup`, the previously written shim (built
// against the old version) references an identifier that no longer exists here, turning
// silent native-library skew into a compile-time error instead of a runtime crash.
const RequireNativeSetup_2_0_0 = "2.0.0"
