// Code generated by alef — DO NOT EDIT.
// alef:hash:b34e5ab9e84761901ce3bc60e131d81b0df458147f11455caca6fc50e1146920
package tspack

// RequireNativeSetup_1_17_0 is a version-skew sentinel referenced by the
// machine-local cgo link shim that `cmd/setup` writes into consumer packages. If this
// module is upgraded without re-running `cmd/setup`, the previously written shim (built
// against the old version) references an identifier that no longer exists here, turning
// silent native-library skew into a compile-time error instead of a runtime crash.
const RequireNativeSetup_1_17_0 = "1.17.0"
