# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:ed107fd5ac47536acf6a019b03d12fb78429507d74fd1d612729d6448c2bd64a
# To regenerate: alef generate
# To verify freshness: alef verify
# frozen_string_literal: true

module TreeSitterLanguagePack
  ## The version string for this package.
  VERSION = "2.0.0"
end
