# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:8fe1732f42d2c94d4531207da9fefc0c7ca59cfc975a4a7dd01c7c248e2a8be6
# To regenerate: alef generate
# To verify freshness: alef verify
# frozen_string_literal: true

module TreeSitterLanguagePack
  ## The version string for this package.
  VERSION = "1.17.0"
end
