// swift-tools-version: 6.0
// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:f967205824ec708be1ec82bbdc762478e43ff8826efc2aeed29c6b25217038b3
// To regenerate: alef generate
// To verify freshness: alef verify

import PackageDescription

let package = Package(
    name: "E2eSwift",
    platforms: [
        .macOS(.v13),
        .iOS(.v16),
    ],
    dependencies: [
        .package(url: "https://github.com/xberg-io/tree-sitter-language-pack", branch: "release/swift/1.17.0"),
    ],
    targets: [
        .testTarget(
            name: "TreeSitterLanguagePackE2ETests",
            dependencies: [.product(name: "TreeSitterLanguagePack", package: "tree-sitter-language-pack")]
        ),
    ]
)
