// swift-tools-version: 6.0
// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:5e6465be1e7b2c67d24038a28a17cd8141fc52c3991ffc48c0cc0f8325eda300
// To regenerate: alef generate
// To verify freshness: alef verify

import PackageDescription

let package = Package(
    name: "E2eSwift",
    platforms: [
        .macOS(.v13),
        .iOS(.v16),
    ],
    dependencies: [
        .package(url: "https://github.com/xberg-io/tree-sitter-language-pack", branch: "release/swift/2.0.0"),
    ],
    targets: [
        .testTarget(
            name: "TreeSitterLanguagePackE2ETests",
            dependencies: [.product(name: "TreeSitterLanguagePack", package: "tree-sitter-language-pack")]
        ),
    ]
)
