// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:c0aec3cf581562f2f14102ce9944f273548e3b1d924781773a6e801c37324632
// To regenerate: alef generate
// To verify freshness: alef verify
#nullable enable

using System.Text.Json;
using System.Text.Json.Serialization;

namespace TreeSitterLanguagePack;

/// <summary>FFI JSON serialization extension methods and options</summary>
internal static class FfiJsonExtensions
{

    /// <summary>Global JsonSerializerOptions for FFI marshalling with relaxed numeric handling.
    /// Supports: enum-to-snake_case conversion, ignoring default values, and reading numeric values from strings.
    /// Used by both trait bridges and callback deserialization.</summary>
    public static readonly JsonSerializerOptions FfiJsonOptions = new()
    {
        Converters = { new JsonStringEnumConverter(JsonNamingPolicy.SnakeCaseLower) },
        DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingDefault,
        NumberHandling = JsonNumberHandling.AllowReadingFromString
    };

    /// <summary>Serialize any object to JSON for FFI marshalling</summary>
    internal static string ToFfiJson<T>(this T value)
    {
        return JsonSerializer.Serialize(value, FfiJsonOptions);
    }

}
