// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:7086899ca5c6937638833c443ce81190d1599fde699c349ecfea6c319a671959
// alef:handle-abi:1
#nullable enable

using System;
using System.Runtime.InteropServices;

namespace TreeSitterLanguagePack;

internal static partial class NativeMethods
{
    private const string LibName = "ts_pack_core_ffi";

    [DllImport(LibName, CallingConvention = CallingConvention.Cdecl, EntryPoint = "ts_pack_download_manager_free")]
    internal static extern void DownloadManagerFree(ulong ptr);

    [DllImport(LibName, CallingConvention = CallingConvention.Cdecl, EntryPoint = "ts_pack_language_free")]
    internal static extern void LanguageFree(ulong ptr);

    [DllImport(LibName, CallingConvention = CallingConvention.Cdecl, EntryPoint = "ts_pack_language_registry_free")]
    internal static extern void LanguageRegistryFree(ulong ptr);

    [DllImport(LibName, CallingConvention = CallingConvention.Cdecl, EntryPoint = "ts_pack_node_free")]
    internal static extern void NodeFree(ulong ptr);

    [DllImport(LibName, CallingConvention = CallingConvention.Cdecl, EntryPoint = "ts_pack_parser_free")]
    internal static extern void ParserFree(ulong ptr);

    [DllImport(LibName, CallingConvention = CallingConvention.Cdecl, EntryPoint = "ts_pack_tree_free")]
    internal static extern void TreeFree(ulong ptr);

    [DllImport(LibName, CallingConvention = CallingConvention.Cdecl, EntryPoint = "ts_pack_tree_cursor_free")]
    internal static extern void TreeCursorFree(ulong ptr);

    [DllImport(LibName, CallingConvention = CallingConvention.Cdecl, EntryPoint = "ts_pack_pack_config_from_json")]
    internal static extern ulong PackConfigFromJson([MarshalAs(UnmanagedType.LPUTF8Str)] string json);

    [DllImport(LibName, CallingConvention = CallingConvention.Cdecl, EntryPoint = "ts_pack_pack_config_free")]
    internal static extern void PackConfigFree(ulong ptr);

    [DllImport(LibName, CallingConvention = CallingConvention.Cdecl, EntryPoint = "ts_pack_process_config_from_json")]
    internal static extern ulong ProcessConfigFromJson([MarshalAs(UnmanagedType.LPUTF8Str)] string json);

    [DllImport(LibName, CallingConvention = CallingConvention.Cdecl, EntryPoint = "ts_pack_process_config_free")]
    internal static extern void ProcessConfigFree(ulong ptr);

    [DllImport(LibName, CallingConvention = CallingConvention.Cdecl, EntryPoint = "ts_pack_byte_range_to_json")]
    internal static extern IntPtr ByteRangeToJson(ulong ptr);

    [DllImport(LibName, CallingConvention = CallingConvention.Cdecl, EntryPoint = "ts_pack_byte_range_free")]
    internal static extern void ByteRangeFree(ulong ptr);

    [DllImport(LibName, CallingConvention = CallingConvention.Cdecl, EntryPoint = "ts_pack_point_to_json")]
    internal static extern IntPtr PointToJson(ulong ptr);

    [DllImport(LibName, CallingConvention = CallingConvention.Cdecl, EntryPoint = "ts_pack_point_free")]
    internal static extern void PointFree(ulong ptr);

    [DllImport(LibName, CallingConvention = CallingConvention.Cdecl, EntryPoint = "ts_pack_process_config_to_json")]
    internal static extern IntPtr ProcessConfigToJson(ulong ptr);

    [DllImport(LibName, CallingConvention = CallingConvention.Cdecl, EntryPoint = "ts_pack_process_result_to_json")]
    internal static extern IntPtr ProcessResultToJson(ulong ptr);

    [DllImport(LibName, CallingConvention = CallingConvention.Cdecl, EntryPoint = "ts_pack_process_result_free")]
    internal static extern void ProcessResultFree(ulong ptr);

    [DllImport(LibName, CallingConvention = CallingConvention.Cdecl, EntryPoint = "ts_pack_available_languages")]
    internal static extern IntPtr AvailableLanguages();

    [DllImport(LibName, CallingConvention = CallingConvention.Cdecl, EntryPoint = "ts_pack_cache_dir")]
    internal static extern IntPtr CacheDir();

    [DllImport(LibName, CallingConvention = CallingConvention.Cdecl, EntryPoint = "ts_pack_clean_cache")]
    internal static extern int CleanCache();

    [DllImport(LibName, CallingConvention = CallingConvention.Cdecl, EntryPoint = "ts_pack_configure")]
    internal static extern int Configure(
        ulong config
    );

    [DllImport(LibName, CallingConvention = CallingConvention.Cdecl, EntryPoint = "ts_pack_detect_language")]
    internal static extern IntPtr DetectLanguage(
        [MarshalAs(UnmanagedType.LPUTF8Str)] string path
    );

    [DllImport(LibName, CallingConvention = CallingConvention.Cdecl, EntryPoint = "ts_pack_detect_language_from_content")]
    internal static extern IntPtr DetectLanguageFromContent(
        [MarshalAs(UnmanagedType.LPUTF8Str)] string content
    );

    [DllImport(LibName, CallingConvention = CallingConvention.Cdecl, EntryPoint = "ts_pack_detect_language_from_extension")]
    internal static extern IntPtr DetectLanguageFromExtension(
        [MarshalAs(UnmanagedType.LPUTF8Str)] string ext
    );

    [DllImport(LibName, CallingConvention = CallingConvention.Cdecl, EntryPoint = "ts_pack_detect_language_from_path")]
    internal static extern IntPtr DetectLanguageFromPath(
        [MarshalAs(UnmanagedType.LPUTF8Str)] string path
    );

    [DllImport(LibName, CallingConvention = CallingConvention.Cdecl, EntryPoint = "ts_pack_download")]
    internal static extern ulong Download(
        IntPtr names
    );

    [DllImport(LibName, CallingConvention = CallingConvention.Cdecl, EntryPoint = "ts_pack_download_all")]
    internal static extern ulong DownloadAll();

    [DllImport(LibName, CallingConvention = CallingConvention.Cdecl, EntryPoint = "ts_pack_download_group")]
    internal static extern ulong DownloadGroup(
        [MarshalAs(UnmanagedType.LPUTF8Str)] string name
    );

    [DllImport(LibName, CallingConvention = CallingConvention.Cdecl, EntryPoint = "ts_pack_downloaded_languages")]
    internal static extern IntPtr DownloadedLanguages();

    [DllImport(LibName, CallingConvention = CallingConvention.Cdecl, EntryPoint = "ts_pack_get_folds_query")]
    internal static extern IntPtr GetFoldsQuery(
        [MarshalAs(UnmanagedType.LPUTF8Str)] string language
    );

    [DllImport(LibName, CallingConvention = CallingConvention.Cdecl, EntryPoint = "ts_pack_get_highlights_query")]
    internal static extern IntPtr GetHighlightsQuery(
        [MarshalAs(UnmanagedType.LPUTF8Str)] string language
    );

    [DllImport(LibName, CallingConvention = CallingConvention.Cdecl, EntryPoint = "ts_pack_get_indents_query")]
    internal static extern IntPtr GetIndentsQuery(
        [MarshalAs(UnmanagedType.LPUTF8Str)] string language
    );

    [DllImport(LibName, CallingConvention = CallingConvention.Cdecl, EntryPoint = "ts_pack_get_injections_query")]
    internal static extern IntPtr GetInjectionsQuery(
        [MarshalAs(UnmanagedType.LPUTF8Str)] string language
    );

    [DllImport(LibName, CallingConvention = CallingConvention.Cdecl, EntryPoint = "ts_pack_get_language")]
    internal static extern IntPtr GetLanguage(
        [MarshalAs(UnmanagedType.LPUTF8Str)] string name
    );

    [DllImport(LibName, CallingConvention = CallingConvention.Cdecl, EntryPoint = "ts_pack_get_locals_query")]
    internal static extern IntPtr GetLocalsQuery(
        [MarshalAs(UnmanagedType.LPUTF8Str)] string language
    );

    [DllImport(LibName, CallingConvention = CallingConvention.Cdecl, EntryPoint = "ts_pack_get_parser")]
    internal static extern ulong GetParser(
        [MarshalAs(UnmanagedType.LPUTF8Str)] string name
    );

    [DllImport(LibName, CallingConvention = CallingConvention.Cdecl, EntryPoint = "ts_pack_get_tags_query")]
    internal static extern IntPtr GetTagsQuery(
        [MarshalAs(UnmanagedType.LPUTF8Str)] string language
    );

    [DllImport(LibName, CallingConvention = CallingConvention.Cdecl, EntryPoint = "ts_pack_has_language")]
    internal static extern int HasLanguage(
        [MarshalAs(UnmanagedType.LPUTF8Str)] string name
    );

    [DllImport(LibName, CallingConvention = CallingConvention.Cdecl, EntryPoint = "ts_pack_init")]
    internal static extern int Init(
        ulong config
    );

    [DllImport(LibName, CallingConvention = CallingConvention.Cdecl, EntryPoint = "ts_pack_language_count")]
    internal static extern ulong LanguageCount();

    [DllImport(LibName, CallingConvention = CallingConvention.Cdecl, EntryPoint = "ts_pack_manifest_groups")]
    internal static extern IntPtr ManifestGroups();

    [DllImport(LibName, CallingConvention = CallingConvention.Cdecl, EntryPoint = "ts_pack_manifest_languages")]
    internal static extern IntPtr ManifestLanguages();

    [DllImport(LibName, CallingConvention = CallingConvention.Cdecl, EntryPoint = "ts_pack_prefetch")]
    internal static extern int Prefetch(
        IntPtr languages
    );

    [DllImport(LibName, CallingConvention = CallingConvention.Cdecl, EntryPoint = "ts_pack_process")]
    internal static extern ulong Process(
        [MarshalAs(UnmanagedType.LPUTF8Str)] string source,
        ulong config
    );

    [DllImport(LibName, CallingConvention = CallingConvention.Cdecl, EntryPoint = "ts_pack_download_manager_new")]
    internal static extern ulong DownloadManagerNew(
        [MarshalAs(UnmanagedType.LPUTF8Str)] string version
    );

    [DllImport(LibName, CallingConvention = CallingConvention.Cdecl, EntryPoint = "ts_pack_download_manager_installed_languages")]
    internal static extern IntPtr DownloadManagerInstalledLanguages(
        ulong handle
    );

    [DllImport(LibName, CallingConvention = CallingConvention.Cdecl, EntryPoint = "ts_pack_download_manager_download_all_best_effort")]
    internal static extern ulong DownloadManagerDownloadAllBestEffort(
        ulong handle
    );

    [DllImport(LibName, CallingConvention = CallingConvention.Cdecl, EntryPoint = "ts_pack_download_manager_clean_cache")]
    internal static extern int DownloadManagerCleanCache(
        ulong handle
    );

    [DllImport(LibName, CallingConvention = CallingConvention.Cdecl, EntryPoint = "ts_pack_language_registry_new")]
    internal static extern ulong LanguageRegistryNew();

    [DllImport(LibName, CallingConvention = CallingConvention.Cdecl, EntryPoint = "ts_pack_language_registry_get_language")]
    internal static extern ulong LanguageRegistryGetLanguage(
        ulong handle,
        [MarshalAs(UnmanagedType.LPUTF8Str)] string name
    );

    [DllImport(LibName, CallingConvention = CallingConvention.Cdecl, EntryPoint = "ts_pack_language_registry_available_languages")]
    internal static extern IntPtr LanguageRegistryAvailableLanguages(
        ulong handle
    );

    [DllImport(LibName, CallingConvention = CallingConvention.Cdecl, EntryPoint = "ts_pack_language_registry_has_parser")]
    internal static extern int LanguageRegistryHasParser(
        ulong handle,
        [MarshalAs(UnmanagedType.LPUTF8Str)] string name
    );

    [DllImport(LibName, CallingConvention = CallingConvention.Cdecl, EntryPoint = "ts_pack_language_registry_has_language")]
    internal static extern int LanguageRegistryHasLanguage(
        ulong handle,
        [MarshalAs(UnmanagedType.LPUTF8Str)] string name
    );

    [DllImport(LibName, CallingConvention = CallingConvention.Cdecl, EntryPoint = "ts_pack_language_registry_language_count")]
    internal static extern ulong LanguageRegistryLanguageCount(
        ulong handle
    );

    [DllImport(LibName, CallingConvention = CallingConvention.Cdecl, EntryPoint = "ts_pack_language_registry_process")]
    internal static extern ulong LanguageRegistryProcess(
        ulong handle,
        [MarshalAs(UnmanagedType.LPUTF8Str)] string source,
        ulong config
    );

    [DllImport(LibName, CallingConvention = CallingConvention.Cdecl, EntryPoint = "ts_pack_language_registry_default")]
    internal static extern ulong LanguageRegistryDefault();

    [DllImport(LibName, CallingConvention = CallingConvention.Cdecl, EntryPoint = "ts_pack_node_kind")]
    internal static extern IntPtr NodeKind(
        ulong handle
    );

    [DllImport(LibName, CallingConvention = CallingConvention.Cdecl, EntryPoint = "ts_pack_node_kind_id")]
    internal static extern ushort NodeKindId(
        ulong handle
    );

    [DllImport(LibName, CallingConvention = CallingConvention.Cdecl, EntryPoint = "ts_pack_node_start_byte")]
    internal static extern ulong NodeStartByte(
        ulong handle
    );

    [DllImport(LibName, CallingConvention = CallingConvention.Cdecl, EntryPoint = "ts_pack_node_end_byte")]
    internal static extern ulong NodeEndByte(
        ulong handle
    );

    [DllImport(LibName, CallingConvention = CallingConvention.Cdecl, EntryPoint = "ts_pack_node_byte_range")]
    internal static extern ulong NodeByteRange(
        ulong handle
    );

    [DllImport(LibName, CallingConvention = CallingConvention.Cdecl, EntryPoint = "ts_pack_node_start_position")]
    internal static extern ulong NodeStartPosition(
        ulong handle
    );

    [DllImport(LibName, CallingConvention = CallingConvention.Cdecl, EntryPoint = "ts_pack_node_end_position")]
    internal static extern ulong NodeEndPosition(
        ulong handle
    );

    [DllImport(LibName, CallingConvention = CallingConvention.Cdecl, EntryPoint = "ts_pack_node_is_named")]
    internal static extern int NodeIsNamed(
        ulong handle
    );

    [DllImport(LibName, CallingConvention = CallingConvention.Cdecl, EntryPoint = "ts_pack_node_is_error")]
    internal static extern int NodeIsError(
        ulong handle
    );

    [DllImport(LibName, CallingConvention = CallingConvention.Cdecl, EntryPoint = "ts_pack_node_is_missing")]
    internal static extern int NodeIsMissing(
        ulong handle
    );

    [DllImport(LibName, CallingConvention = CallingConvention.Cdecl, EntryPoint = "ts_pack_node_is_extra")]
    internal static extern int NodeIsExtra(
        ulong handle
    );

    [DllImport(LibName, CallingConvention = CallingConvention.Cdecl, EntryPoint = "ts_pack_node_has_error")]
    internal static extern int NodeHasError(
        ulong handle
    );

    [DllImport(LibName, CallingConvention = CallingConvention.Cdecl, EntryPoint = "ts_pack_node_parent")]
    internal static extern ulong NodeParent(
        ulong handle
    );

    [DllImport(LibName, CallingConvention = CallingConvention.Cdecl, EntryPoint = "ts_pack_node_child")]
    internal static extern ulong NodeChild(
        ulong handle,
        uint index
    );

    [DllImport(LibName, CallingConvention = CallingConvention.Cdecl, EntryPoint = "ts_pack_node_child_count")]
    internal static extern ulong NodeChildCount(
        ulong handle
    );

    [DllImport(LibName, CallingConvention = CallingConvention.Cdecl, EntryPoint = "ts_pack_node_named_child")]
    internal static extern ulong NodeNamedChild(
        ulong handle,
        uint index
    );

    [DllImport(LibName, CallingConvention = CallingConvention.Cdecl, EntryPoint = "ts_pack_node_named_child_count")]
    internal static extern ulong NodeNamedChildCount(
        ulong handle
    );

    [DllImport(LibName, CallingConvention = CallingConvention.Cdecl, EntryPoint = "ts_pack_node_child_by_field_name")]
    internal static extern ulong NodeChildByFieldName(
        ulong handle,
        [MarshalAs(UnmanagedType.LPUTF8Str)] string name
    );

    [DllImport(LibName, CallingConvention = CallingConvention.Cdecl, EntryPoint = "ts_pack_node_to_sexp")]
    internal static extern IntPtr NodeToSexp(
        ulong handle
    );

    [DllImport(LibName, CallingConvention = CallingConvention.Cdecl, EntryPoint = "ts_pack_node_walk")]
    internal static extern ulong NodeWalk(
        ulong handle
    );

    [DllImport(LibName, CallingConvention = CallingConvention.Cdecl, EntryPoint = "ts_pack_parser_new")]
    internal static extern ulong ParserNew();

    [DllImport(LibName, CallingConvention = CallingConvention.Cdecl, EntryPoint = "ts_pack_parser_set_max_source_bytes")]
    internal static extern void ParserSetMaxSourceBytes(
        ulong handle,
        ulong maxBytes
    );

    [DllImport(LibName, CallingConvention = CallingConvention.Cdecl, EntryPoint = "ts_pack_parser_set_parse_timeout_ms")]
    internal static extern void ParserSetParseTimeoutMs(
        ulong handle,
        ulong timeoutMs
    );

    [DllImport(LibName, CallingConvention = CallingConvention.Cdecl, EntryPoint = "ts_pack_parser_set_language")]
    internal static extern int ParserSetLanguage(
        ulong handle,
        [MarshalAs(UnmanagedType.LPUTF8Str)] string name
    );

    [DllImport(LibName, CallingConvention = CallingConvention.Cdecl, EntryPoint = "ts_pack_parser_parse")]
    internal static extern ulong ParserParse(
        ulong handle,
        [MarshalAs(UnmanagedType.LPUTF8Str)] string source
    );

    [DllImport(LibName, CallingConvention = CallingConvention.Cdecl, EntryPoint = "ts_pack_parser_parse_bytes")]
    internal static extern ulong ParserParseBytes(
        ulong handle,
        IntPtr source,
        UIntPtr sourceLen
    );

    [DllImport(LibName, CallingConvention = CallingConvention.Cdecl, EntryPoint = "ts_pack_parser_reset")]
    internal static extern void ParserReset(
        ulong handle
    );

    [DllImport(LibName, CallingConvention = CallingConvention.Cdecl, EntryPoint = "ts_pack_parser_default")]
    internal static extern ulong ParserDefault();

    [DllImport(LibName, CallingConvention = CallingConvention.Cdecl, EntryPoint = "ts_pack_process_config_default")]
    internal static extern ulong ProcessConfigDefault();

    [DllImport(LibName, CallingConvention = CallingConvention.Cdecl, EntryPoint = "ts_pack_process_config_with_chunking")]
    internal static extern ulong ProcessConfigWithChunking(
        ulong handle,
        ulong maxSize
    );

    [DllImport(LibName, CallingConvention = CallingConvention.Cdecl, EntryPoint = "ts_pack_process_config_all")]
    internal static extern ulong ProcessConfigAll(
        ulong handle
    );

    [DllImport(LibName, CallingConvention = CallingConvention.Cdecl, EntryPoint = "ts_pack_process_config_minimal")]
    internal static extern ulong ProcessConfigMinimal(
        ulong handle
    );

    [DllImport(LibName, CallingConvention = CallingConvention.Cdecl, EntryPoint = "ts_pack_process_config_with_data_extraction")]
    internal static extern ulong ProcessConfigWithDataExtraction(
        ulong handle,
        int enabled
    );

    [DllImport(LibName, CallingConvention = CallingConvention.Cdecl, EntryPoint = "ts_pack_process_config_with_max_source_bytes")]
    internal static extern ulong ProcessConfigWithMaxSourceBytes(
        ulong handle,
        ulong maxBytes
    );

    [DllImport(LibName, CallingConvention = CallingConvention.Cdecl, EntryPoint = "ts_pack_process_config_with_parse_timeout_ms")]
    internal static extern ulong ProcessConfigWithParseTimeoutMs(
        ulong handle,
        ulong timeoutMs
    );

    [DllImport(LibName, CallingConvention = CallingConvention.Cdecl, EntryPoint = "ts_pack_process_config_validate")]
    internal static extern int ProcessConfigValidate(
        ulong handle
    );

    [DllImport(LibName, CallingConvention = CallingConvention.Cdecl, EntryPoint = "ts_pack_tree_root_node")]
    internal static extern ulong TreeRootNode(
        ulong handle
    );

    [DllImport(LibName, CallingConvention = CallingConvention.Cdecl, EntryPoint = "ts_pack_tree_walk")]
    internal static extern ulong TreeWalk(
        ulong handle
    );

    [DllImport(LibName, CallingConvention = CallingConvention.Cdecl, EntryPoint = "ts_pack_tree_cursor_node")]
    internal static extern ulong TreeCursorNode(
        ulong handle
    );

    [DllImport(LibName, CallingConvention = CallingConvention.Cdecl, EntryPoint = "ts_pack_tree_cursor_goto_first_child")]
    internal static extern int TreeCursorGotoFirstChild(
        ulong handle
    );

    [DllImport(LibName, CallingConvention = CallingConvention.Cdecl, EntryPoint = "ts_pack_tree_cursor_goto_parent")]
    internal static extern int TreeCursorGotoParent(
        ulong handle
    );

    [DllImport(LibName, CallingConvention = CallingConvention.Cdecl, EntryPoint = "ts_pack_tree_cursor_goto_next_sibling")]
    internal static extern int TreeCursorGotoNextSibling(
        ulong handle
    );

    [DllImport(LibName, CallingConvention = CallingConvention.Cdecl, EntryPoint = "ts_pack_tree_cursor_field_name")]
    internal static extern IntPtr TreeCursorFieldName(
        ulong handle
    );

    [DllImport(LibName, CallingConvention = CallingConvention.Cdecl, EntryPoint = "ts_pack_last_error_code")]
    internal static extern int LastErrorCode();

    [DllImport(LibName, CallingConvention = CallingConvention.Cdecl, EntryPoint = "ts_pack_last_error_context")]
    internal static extern IntPtr LastErrorContext();

    [DllImport(LibName, CallingConvention = CallingConvention.Cdecl, EntryPoint = "ts_pack_free_string")]
    internal static extern void FreeString(IntPtr ptr);

}
